### ISSUE TITLE
ImportError: cannot import name 'PILLOW_VERSION' from 'PIL'

### ISSUE THREAD

**Issue by iTomxy** [gregunz/invertransforms#3]
```
Traceback (most recent call last):
  File "/home/tom/codes/cbm24sasnil/test.py", line 4, in <module>
    from data import binarise_totalseg_label, val_trfm
  File "/home/tom/codes/cbm24sasnil/data.py", line 13, in <module>
    import invertransforms as T
  File "/share/tom/miniconda3/envs/cu116_pt1131/lib/python3.9/site-packages/invertransforms/__init__.py", line 46, in <module>
    from .affine import Affine, RandomAffine, RandomRotation, Rotation
  File "/share/tom/miniconda3/envs/cu116_pt1131/lib/python3.9/site-packages/invertransforms/affine.py", line 8, in <module>
    from PIL import Image, PILLOW_VERSION
ImportError: cannot import name 'PILLOW_VERSION' from 'PIL' (/share/tom/miniconda3/envs/cu116_pt1131/lib/python3.9/site-packages/PIL/__init__.py)
```
Packages version:
- invertransforms 0.2.1
- Pillow 10.0.1

---

1. [Could not import PILLOW_VERSION from PIL](https://stackoverflow.com/questions/59659146/could-not-import-pillow-version-from-pil)

**Comment by iTomxy** [comment]
Install by `pip install git+https://github.com/gregunz/invertransforms` instead of `pip install invertransforms` solves the problem.
